#!/bin/sh
# Generated by vim-plug
# Thu 26 Nov 23:21:34 2015

vim +PlugUpdate +qa

PLUG_HOME=~/nvim/plugged

cd /Users/ian/.fzf/ && git reset --hard e1df876
cd $PLUG_HOME/VimCompletesMe/ && git reset --hard 1091333
cd $PLUG_HOME/auto-pairs/ && git reset --hard b647ef5
cd $PLUG_HOME/dash.vim/ && git reset --hard f74a0a3
cd $PLUG_HOME/differ/ && git reset --hard 491324c
cd $PLUG_HOME/fzf.vim/ && git reset --hard 9a45d70
cd $PLUG_HOME/gruvbox/ && git reset --hard a099b59
cd $PLUG_HOME/html5.vim/ && git reset --hard ad38231
cd $PLUG_HOME/neomake/ && git reset --hard c1de90f
cd $PLUG_HOME/quick-scope/ && git reset --hard d5882cb
cd $PLUG_HOME/scss-syntax.vim/ && git reset --hard 35f47ff
cd $PLUG_HOME/splitjoin.vim/ && git reset --hard 10e7568
cd $PLUG_HOME/targets.vim/ && git reset --hard d111928
cd $PLUG_HOME/undotree/ && git reset --hard 74874d9
cd $PLUG_HOME/vim-capslock/ && git reset --hard 6c5b03e
cd $PLUG_HOME/vim-coffee-script/ && git reset --hard 32fe889
cd $PLUG_HOME/vim-commentary/ && git reset --hard e0f4850
cd $PLUG_HOME/vim-dentures/ && git reset --hard b0575f7
cd $PLUG_HOME/vim-endwise/ && git reset --hard f06abe3
cd $PLUG_HOME/vim-fugitive/ && git reset --hard 1ecd12d
cd $PLUG_HOME/vim-grepper/ && git reset --hard b004cb9
cd $PLUG_HOME/vim-javascript/ && git reset --hard 1d8c267
cd $PLUG_HOME/vim-peekaboo/ && git reset --hard b14a749
cd $PLUG_HOME/vim-qf/ && git reset --hard fa5de63
cd $PLUG_HOME/vim-rails/ && git reset --hard e25769a
cd $PLUG_HOME/vim-rake/ && git reset --hard 82ad455
cd $PLUG_HOME/vim-repeat/ && git reset --hard 7a6675f
cd $PLUG_HOME/vim-ruby/ && git reset --hard 7a04694
cd $PLUG_HOME/vim-sayonara/ && git reset --hard 1537469
cd $PLUG_HOME/vim-sensible/ && git reset --hard 26f8783
cd $PLUG_HOME/vim-surround/ && git reset --hard 2d05440
cd $PLUG_HOME/vim-textobj-erb/ && git reset --hard 03e3840
cd $PLUG_HOME/vim-textobj-ruby/ && git reset --hard e955714
cd $PLUG_HOME/vim-textobj-user/ && git reset --hard a305416
cd $PLUG_HOME/vim-tmux-focus-events/ && git reset --hard eccc2f5
cd $PLUG_HOME/vim-unimpaired/ && git reset --hard 23f471a
cd $PLUG_HOME/vim-vinegar/ && git reset --hard a5f776c
cd $PLUG_HOME/vimux/ && git reset --hard 2285cef

