#!/bin/sh
# Generated by vim-plug
# Wed Oct 14 15:23:56 2015

vim +PlugUpdate +qa

PLUG_HOME=~/.vim/plugged

cd ~/.fzf/ && git reset --hard ae04f56
cd $PLUG_HOME/VimCompletesMe/ && git reset --hard 1091333
cd $PLUG_HOME/auto-pairs/ && git reset --hard b647ef5
cd $PLUG_HOME/base16-vim/ && git reset --hard e711e9b
cd $PLUG_HOME/dash.vim/ && git reset --hard c96bf09
cd $PLUG_HOME/easybuffer.vim/ && git reset --hard 64bd1d5
cd $PLUG_HOME/fzf.vim/ && git reset --hard 2977f08
cd $PLUG_HOME/html5.vim/ && git reset --hard 76da614
cd $PLUG_HOME/quick-scope/ && git reset --hard d5882cb
cd $PLUG_HOME/rust.vim/ && git reset --hard 566fa06
cd $PLUG_HOME/scss-syntax.vim/ && git reset --hard 35f47ff
cd $PLUG_HOME/splitjoin.vim/ && git reset --hard 0becb72
cd $PLUG_HOME/syntastic/ && git reset --hard d36bc78
cd $PLUG_HOME/targets.vim/ && git reset --hard 163d75c
cd $PLUG_HOME/undotree/ && git reset --hard 8ff701a
cd $PLUG_HOME/vim-airline/ && git reset --hard 8c30610
cd $PLUG_HOME/vim-coffee-script/ && git reset --hard 32fe889
cd $PLUG_HOME/vim-colors-solarized/ && git reset --hard 528a59f
cd $PLUG_HOME/vim-commentary/ && git reset --hard e0f4850
cd $PLUG_HOME/vim-elixir/ && git reset --hard f2c747d
cd $PLUG_HOME/vim-endwise/ && git reset --hard f06abe3
cd $PLUG_HOME/vim-fugitive/ && git reset --hard b5188a1
cd $PLUG_HOME/vim-gitgutter/ && git reset --hard a30ee7f
cd $PLUG_HOME/vim-go/ && git reset --hard 17b57b9
cd $PLUG_HOME/vim-gtfo/ && git reset --hard b722e86
cd $PLUG_HOME/vim-javascript/ && git reset --hard 1d8c267
cd $PLUG_HOME/vim-rails/ && git reset --hard 2156c58
cd $PLUG_HOME/vim-rake/ && git reset --hard 82ad455
cd $PLUG_HOME/vim-repeat/ && git reset --hard 7a6675f
cd $PLUG_HOME/vim-ruby/ && git reset --hard 3db2f83
cd $PLUG_HOME/vim-sayonara/ && git reset --hard 0eec4bd
cd $PLUG_HOME/vim-sensible/ && git reset --hard 26f8783
cd $PLUG_HOME/vim-signature/ && git reset --hard d563023
cd $PLUG_HOME/vim-surround/ && git reset --hard 2d05440
cd $PLUG_HOME/vim-textobj-erb/ && git reset --hard 03e3840
cd $PLUG_HOME/vim-textobj-ruby/ && git reset --hard e955714
cd $PLUG_HOME/vim-textobj-user/ && git reset --hard a305416
cd $PLUG_HOME/vim-tmux-focus-events/ && git reset --hard bb36f0c
cd $PLUG_HOME/vim-unimpaired/ && git reset --hard 23f471a
cd $PLUG_HOME/vim-vinegar/ && git reset --hard ebd2239
cd $PLUG_HOME/vimux/ && git reset --hard 2285cef

