#!/bin/sh
# Generated by vim-plug
# Fri Mar 18 14:43:39 2016

vim +PlugUpdate +qa

PLUG_HOME=~/nvim/plugged

cd /Users/ian/.fzf/ && git reset --hard e72a360
cd $PLUG_HOME/FastFold/ && git reset --hard 0ec847d
cd $PLUG_HOME/VimCompletesMe/ && git reset --hard 10b91d5
cd $PLUG_HOME/auto-pairs/ && git reset --hard b647ef5
cd $PLUG_HOME/cobalt2.vim/ && git reset --hard 68f5f57
cd $PLUG_HOME/fzf.vim/ && git reset --hard be01b64
cd $PLUG_HOME/gruvbox/ && git reset --hard 26f4382
cd $PLUG_HOME/gv.vim/ && git reset --hard 3fa14b6
cd $PLUG_HOME/html5.vim/ && git reset --hard fccd580
cd $PLUG_HOME/neomake/ && git reset --hard e3f6fc5
cd $PLUG_HOME/onedark.vim/ && git reset --hard 5640329
cd $PLUG_HOME/quick-scope/ && git reset --hard d5882cb
cd $PLUG_HOME/rust.vim/ && git reset --hard 9924277
cd $PLUG_HOME/scss-syntax.vim/ && git reset --hard a834e43
cd $PLUG_HOME/targets.vim/ && git reset --hard ab423a1
cd $PLUG_HOME/undotree/ && git reset --hard 39e5cf0
cd $PLUG_HOME/vim-coffee-script/ && git reset --hard 32fe889
cd $PLUG_HOME/vim-commentary/ && git reset --hard 4dcfc31
cd $PLUG_HOME/vim-dirvish/ && git reset --hard af6ce34
cd $PLUG_HOME/vim-endwise/ && git reset --hard 0067ced
cd $PLUG_HOME/vim-fetch/ && git reset --hard ce1bfad
cd $PLUG_HOME/vim-fugitive/ && git reset --hard 9835920
cd $PLUG_HOME/vim-gitgutter/ && git reset --hard 8b046bd
cd $PLUG_HOME/vim-grepper/ && git reset --hard f64d41d
cd $PLUG_HOME/vim-javascript/ && git reset --hard 1d8c267
cd $PLUG_HOME/vim-lion/ && git reset --hard c97dfd4
cd $PLUG_HOME/vim-oblique/ && git reset --hard 9b05453
cd $PLUG_HOME/vim-operator-replace/ && git reset --hard 1345a55
cd $PLUG_HOME/vim-operator-user/ && git reset --hard c3dfd41
cd $PLUG_HOME/vim-pseudocl/ && git reset --hard 3bf5a82
cd $PLUG_HOME/vim-qf/ && git reset --hard fa5de63
cd $PLUG_HOME/vim-racer/ && git reset --hard ec26ab4
cd $PLUG_HOME/vim-rails/ && git reset --hard df64206
cd $PLUG_HOME/vim-repeat/ && git reset --hard 7a6675f
cd $PLUG_HOME/vim-ruby/ && git reset --hard 666adb5
cd $PLUG_HOME/vim-sayonara/ && git reset --hard 1537469
cd $PLUG_HOME/vim-surround/ && git reset --hard 2d05440
cd $PLUG_HOME/vim-textobj-argument/ && git reset --hard 179a8d4
cd $PLUG_HOME/vim-textobj-ruby/ && git reset --hard e955714
cd $PLUG_HOME/vim-textobj-user/ && git reset --hard a305416
cd $PLUG_HOME/vim-tmux-focus-events/ && git reset --hard eccc2f5
cd $PLUG_HOME/vim-tmux/ && git reset --hard 876f0bd
cd $PLUG_HOME/vim-toml/ && git reset --hard f6f79f3
cd $PLUG_HOME/vim-unimpaired/ && git reset --hard 11dc568
cd $PLUG_HOME/vimux/ && git reset --hard 2285cef

