#!/bin/sh
# Generated by vim-plug
# Wed Apr 13 14:54:53 2016

vim +PlugUpdate +qa

PLUG_HOME=~/nvim/plugged

cd /Users/ian/.fzf/ && git reset --hard 935e986
cd $PLUG_HOME/FastFold/ && git reset --hard d080780
cd $PLUG_HOME/VimCompletesMe/ && git reset --hard 10b91d5
cd $PLUG_HOME/auto-pairs/ && git reset --hard 5979999
cd $PLUG_HOME/fzf.vim/ && git reset --hard 757ab1c
cd $PLUG_HOME/gruvbox/ && git reset --hard 26f4382
cd $PLUG_HOME/gv.vim/ && git reset --hard 2f5323e
cd $PLUG_HOME/html5.vim/ && git reset --hard fccd580
cd $PLUG_HOME/neomake/ && git reset --hard efed015
cd $PLUG_HOME/quick-scope/ && git reset --hard d5882cb
cd $PLUG_HOME/rust.vim/ && git reset --hard 115d321
cd $PLUG_HOME/scss-syntax.vim/ && git reset --hard bf65d5d
cd $PLUG_HOME/targets.vim/ && git reset --hard f6f2d66
cd $PLUG_HOME/undotree/ && git reset --hard e5a01b2
cd $PLUG_HOME/vim-coffee-script/ && git reset --hard 32fe889
cd $PLUG_HOME/vim-commentary/ && git reset --hard 73e0d9a
cd $PLUG_HOME/vim-dirvish/ && git reset --hard c1654d5
cd $PLUG_HOME/vim-endwise/ && git reset --hard 0067ced
cd $PLUG_HOME/vim-fetch/ && git reset --hard ce1bfad
cd $PLUG_HOME/vim-fugitive/ && git reset --hard 841adb4
cd $PLUG_HOME/vim-gitgutter/ && git reset --hard 78d83c7
cd $PLUG_HOME/vim-grepper/ && git reset --hard 57f7669
cd $PLUG_HOME/vim-javascript/ && git reset --hard 1833982
cd $PLUG_HOME/vim-lion/ && git reset --hard c97dfd4
cd $PLUG_HOME/vim-oblique/ && git reset --hard c9c93ee
cd $PLUG_HOME/vim-operator-replace/ && git reset --hard 1345a55
cd $PLUG_HOME/vim-operator-user/ && git reset --hard c3dfd41
cd $PLUG_HOME/vim-pseudocl/ && git reset --hard 3bf5a82
cd $PLUG_HOME/vim-qf/ && git reset --hard e5db57c
cd $PLUG_HOME/vim-racer/ && git reset --hard 54f10ee
cd $PLUG_HOME/vim-rails/ && git reset --hard b131dc9
cd $PLUG_HOME/vim-repeat/ && git reset --hard 7a6675f
cd $PLUG_HOME/vim-ruby/ && git reset --hard 666adb5
cd $PLUG_HOME/vim-sayonara/ && git reset --hard 1537469
cd $PLUG_HOME/vim-surround/ && git reset --hard 2d05440
cd $PLUG_HOME/vim-textobj-argument/ && git reset --hard 179a8d4
cd $PLUG_HOME/vim-textobj-ruby/ && git reset --hard e955714
cd $PLUG_HOME/vim-textobj-user/ && git reset --hard a305416
cd $PLUG_HOME/vim-tmux-focus-events/ && git reset --hard eccc2f5
cd $PLUG_HOME/vim-tmux/ && git reset --hard 876f0bd
cd $PLUG_HOME/vim-toml/ && git reset --hard f6f79f3
cd $PLUG_HOME/vim-unimpaired/ && git reset --hard 11dc568
cd $PLUG_HOME/vim-visual-page-percent/ && git reset --hard 009011a
cd $PLUG_HOME/vimux/ && git reset --hard 2285cef

